AMREX_HOME ?= ../../amrex

PRECISION  = DOUBLE
PROFILE    = FALSE

DEBUG      = TRUE
DEBUG      = FALSE
BL_NO_FORT = TRUE

#DIM        = 2
DIM       = 3

COMP	   = clang 

USE_MPI    = TRUE
USE_OMP    = FALSE 
USE_CUDA   = FALSE

Bpack   := ./Make.package 
Blocs   := . 

include ../Make.echemAMR
