AMREX_HOME ?= ../../amrex
ECHEM_DIR   ?= ../../../echemAMR

PRECISION  = DOUBLE
PROFILE    = FALSE

DEBUG      = TRUE
DEBUG      = FALSE

#DIM        = 2
DIM       = 3

COMP	   = gnu

USE_MPI    = TRUE
USE_OMP    = FALSE 
USE_CUDA   = FALSE

Bpack   := ./Make.package 
Blocs   := . 

include ${ECHEM_DIR}/regression_tests/Make.echemAMR
