name: CI_echemamr                                                                                                                                          
on: 
   push:
     branches: [ main ]
   pull_request:
     branches: [ main ]

jobs:
  cputest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: System Dependencies
      run: | 
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
        build-essential g++ gfortran libopenmpi-dev openmpi-bin
        git clone https://github.com/hypre-space/hypre.git
        cd hypre/src
        ./configure
        make install
    - name: Build Regression
      working-directory: ./regression_tests
      run: |
        cd DriftDiffuse1d
        make -j 2 COMP=gnu
        cd ..
        cd openCircuitElectrode
        make -j 2 COMP=gnu
        cd ..
        cd anodeElectrolyte
        make -j 2 COMP=gnu
        cd ..
        cd CEA
        make -j 2 COMP=gnu
    - name: Build Models
      working-directory: ./models
      run: |
        cd Microstructure_Cphi
        make -j 2 COMP=gnu
    - name: Run Regression
      working-directory: ./regression_tests
      run: |
          cd DriftDiffuse1d
          mpirun -n 2 ./echemAMR3d.gnu.MPI.ex inputs_x
          mpirun -n 2 ./echemAMR3d.gnu.MPI.ex inputs_y
          mpirun -n 2 ./echemAMR3d.gnu.MPI.ex inputs_z
          cd ..
          cd openCircuitElectrode
          mpirun -n 2 ./echemAMR3d.gnu.MPI.ex inputs_x
          mpirun -n 2 ./echemAMR3d.gnu.MPI.ex inputs_y
          mpirun -n 2 ./echemAMR3d.gnu.MPI.ex inputs_z
          cd ..
          cd anodeElectrolyte
          mpirun -n 2 ./echemAMR3d.gnu.MPI.ex inputs_x
          mpirun -n 2 ./echemAMR3d.gnu.MPI.ex inputs_y
          mpirun -n 2 ./echemAMR3d.gnu.MPI.ex inputs_z
          cd ..
          cd CEA
          mpirun -n 2 ./echemAMR3d.gnu.MPI.ex inputs_x
          mpirun -n 2 ./echemAMR3d.gnu.MPI.ex inputs_y
          mpirun -n 2 ./echemAMR3d.gnu.MPI.ex inputs_z
    - name: Run Model
      working-directory: ./models
      run: |
          cd Microstructure_Cphi
          mpirun -n 2 ./echemAMR3d.gnu.DEBUG.MPI.ex inputs_CESEAtest
  gputest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: System Dependencies
      run: | 
          export DEBIAN_FRONTEND=noninteractive
          wget -q -O - https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub | sudo apt-key add -
          echo "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64 /" | sudo tee /etc/apt/sources.list.d/cuda.list
          echo "deb https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64 /" | sudo tee /etc/apt/sources.list.d/nvidia-ml.list
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
          g++ gfortran libopenmpi-dev openmpi-bin cuda-command-line-tools-11-1 \
          cuda-compiler-11-1 cuda-minimal-build-11-1 \
          cuda-nvml-dev-11-1 cuda-nvtx-11-1 libcurand-dev-11-1 cuda-cupti-dev-11-1
          git clone https://github.com/hypre-space/hypre.git
          cd hypre/src
          ./configure --with-cuda --enable-unified-memory
          make install
    - name: Build Regression
      working-directory: ./regression_tests
      run: |
        export PATH=/usr/local/nvidia/bin:/usr/local/cuda-11.1/bin:${PATH}
        export LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda-11.1/lib:${LD_LIBRARY_PATH}
        cd DriftDiffuse1d
        make -j 2 COMP=gnu USE_CUDA=TRUE
        cd ..
        cd openCircuitElectrode
        make -j 2 COMP=gnu USE_CUDA=TRUE
        cd ..
        cd anodeElectrolyte
        make -j 2 COMP=gnu USE_CUDA=TRUE
        cd ..
        cd CEA
        make -j 2 COMP=gnu USE_CUDA=TRUE
    - name: Build Model
      working-directory: ./models
      run: |
        export PATH=/usr/local/nvidia/bin:/usr/local/cuda-11.1/bin:${PATH}
        export LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda-11.1/lib:${LD_LIBRARY_PATH}
        cd Microstructure_Cphi
        make -j 2 COMP=gnu USE_CUDA=TRUE
