name: CI_echemamr                                                                                                                                          
on: 
   push:
     branches: [ gpufixes ]
   pull_request:
     branches: [ gpufixes ]

jobs:
  driftdiffuse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: System Dependencies
      run: | 
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
        build-essential g++ gfortran libopenmpi-dev openmpi-bin
    - name: Build
      working-directory: ./test/DriftDiffuse1d
      run: |
        make -j 2 COMP=gnu
    - name: Run
      working-directory: ./test/DriftDiffuse1d
      run: |
          mpirun -n 2 ./echemAMR3d.gnu.MPI.ex inputs_x
          mpirun -n 2 ./echemAMR3d.gnu.MPI.ex inputs_y
          mpirun -n 2 ./echemAMR3d.gnu.MPI.ex inputs_z
  CUDAdriftdiffuse:
    needs: Formatting
    runs-on: ubuntu-latest
    name: CUDAgpu
    strategy:
      matrix:
        #cuda_pkg: [11-1, 10-2]
        cuda_pkg: [11-1]
        include:
          - cuda_ver: "11.1"
            cuda_pkg: 11-1
            cuda_extra: libcurand-dev-11-1 cuda-cupti-dev-11-1
          #- cuda_ver: "10.2"
          #  cuda_pkg: 10-2
          #  cuda_extra: cuda-curand-dev-10-2 cuda-cupti-dev-10-2
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: System Dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          wget -q -O - https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub | sudo apt-key add -
          echo "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64 /" | sudo tee /etc/apt/sources.list.d/cuda.list
          echo "deb https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64 /" | sudo tee /etc/apt/sources.list.d/nvidia-ml.list
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
              libopenmpi-dev cuda-command-line-tools-${{matrix.cuda_pkg}} \
              cuda-compiler-${{matrix.cuda_pkg}} cuda-minimal-build-${{matrix.cuda_pkg}} \
              cuda-nvml-dev-${{matrix.cuda_pkg}} cuda-nvtx-${{matrix.cuda_pkg}} ${{matrix.cuda_extra}}
      - name: Build
        working-directory: ./test/DriftDiffuse1d
        run: |
            make -j 2 COMP=gnu USE_CUDA=TRUE
      - name: runcase
        working-directory: ./test/DriftDiffuse1d
        run: |
          mpirun -n 2 ./echemAMR3d.gnu.MPI.ex inputs_x
          mpirun -n 2 ./echemAMR3d.gnu.MPI.ex inputs_y
          mpirun -n 2 ./echemAMR3d.gnu.MPI.ex inputs_z
