name: CI_echemamr                                                                                                                                          
on: 
   push:
     branches: [ gpuci ]
   pull_request:
     branches: [ gpuci ]

jobs:
  cputest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: System Dependencies
      run: | 
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
        build-essential g++ gfortran libopenmpi-dev openmpi-bin
        git clone https://github.com/hypre-space/hypre.git
        cd hypre/src
        ./configure
        make install
    - name: Build Regression
      working-directory: ./regression_tests
      run: |
        cd DriftDiffuse1d
        make -j 2 COMP=gnu
        cd ..
        cd openCircuitElectrode
        make -j 2 COMP=gnu
        cd ..
        cd anodeElectrolyte
        make -j 2 COMP=gnu
        cd ..
        cd CEA
        make -j 2 COMP=gnu
    - name: Build Models
      working-directory: ./models
      run: |
        cd Microstructure
        make -j 2 COMP=gnu DEBUG=FALSE
    - name: Run Regression
      working-directory: ./regression_tests
      run: |
          cd DriftDiffuse1d
          mpirun -n 1 ./echemAMR3d.gnu.MPI.ex inputs_x
          mpirun -n 1 ./echemAMR3d.gnu.MPI.ex inputs_y
          mpirun -n 1 ./echemAMR3d.gnu.MPI.ex inputs_z
          cd ..
          cd openCircuitElectrode
          mpirun -n 1 ./echemAMR3d.gnu.MPI.ex inputs_x
          mpirun -n 1 ./echemAMR3d.gnu.MPI.ex inputs_y
          mpirun -n 1 ./echemAMR3d.gnu.MPI.ex inputs_z
          cd ..
          cd anodeElectrolyte
          mpirun -n 1 ./echemAMR3d.gnu.MPI.ex inputs_x
          mpirun -n 1 ./echemAMR3d.gnu.MPI.ex inputs_y
          mpirun -n 1 ./echemAMR3d.gnu.MPI.ex inputs_z
          cd ..
          cd CEA
          mpirun -n 1 ./echemAMR3d.gnu.MPI.ex inputs_x
          mpirun -n 1 ./echemAMR3d.gnu.MPI.ex inputs_y
          mpirun -n 1 ./echemAMR3d.gnu.MPI.ex inputs_z
    - name: Run Model
      working-directory: ./models
      run: |
          cd Microstructure
          mpirun -n 1 ./echemAMR3d.gnu.TPROF.MPI.ex inputs_CESEA_case1
